version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: stock_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - mongodb
    environment:
      - POSTGRES_DB=stock_data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017

volumes:
  pgdata:
  mongodbdata:
